server:
  port: 8080

#Para registrar a instância da loja no Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Url que acessa para pegar as informações de Authorization do usuário
security:
  oauth2:
    resource:
      user-info-uri:
        http://localhost:8088/user

#Para transitar o token pelo Feign Client
hystrix:
  shareSecurityContext: true